### ISSUE TITLE
Output in binary format

### ISSUE THREAD

**Issue by f481o** [toastedcrumpets/DynamO#64] opened 2020-09-14 13:27 UTC
Dear all,
is it possible to save output files in binary format?
If yes, is it then possible to use the output files in binary format as input for a new simulation?
Thank you very much.
Kind regards,
Fabio

**Comment by toastedcrumpets** [comment] 2020-09-14 14:10
Hi,
By default, they're saved as compressed XML files. This means they are "binary".
What do you want to achieve with binary saving? The compression gives you the space saving and disk performance. Loading is a little slower but even for massive systems its only a few seconds. Shouldn't be a problem if you're running simulations longer than a few minutes.
Kind regards,
Marcus

**Comment by f481o** [comment] 2020-09-14 14:28
Dear Marcus,
Thank you very much for your reply.
I was checking if restarting simulations from an intermediate output file was giving the same history.
Following your reply it should be so.
I thought differently because I picked up the wrong file.
Kind regards,
Fabio

**Comment by f481o** [comment] 2020-09-15 08:17
I tried to restart a simulation from an intermediate output using the right file this time, but still I'm not getting the same history, which I should considering that xml files are in binary format.

What I do is to decompress an output file, for example with the following command:
bzip2 -dk Snapshot.5e.xml.bz2
and using it as input file for a new simulation (keeping the same options), but the new output files (Snapshot.0e.xml.bz2, Snapshot.1e.xml.bz2, etc.) I get are different from all the original Snapshot.6e.xml.bz2, Snapshot.7e.xml.bz2, etc. 

Am I doing something wrong?

Thank you very much for your help.
Kind regards,
Fabio

**Comment by toastedcrumpets** [comment] 2020-09-15 12:35
You don't need to decompress the snapshots, dynamo will load compressed files. While the files are stored in text, the output is at full precision. So the issue you describe is not about the accuracy of restarting. The issue is that the output files contain all data from the simulation run so far. They are snapshots of the whole simulation data at that particular time (plus a config file). Restarting the simulation at the snapshot does not reload the output.
I think this is more logical? Hope this helps!

**Comment by f481o** [comment] 2020-09-15 16:06
Thank you for your reply.
Therefore, if I understand well, you are saying that it is not possible to restart simulations from a Snapshot to get the exact same history because the program would need to load also other output information included in the corresponding Snapshot.output file.
In principle, it should be enough to know the position and velocities of all particles at a specific time (i.e., one single Snapshot as binary file) in order to compute the dynamics at subsequent times (and to compute all possible quantities associated with the system).
Am I right?

**Comment by toastedcrumpets** [comment] 2020-09-15 20:28
Yes, everything you say is correct. The snapshots contain the state of the system at the time of the snapshot, not the collected data. The snapshot allows you to continue the simulation, almost exactly as it was (there are some differences due to rounding, but these are reduced as far as possible).

I'll close this issue now as I think it is resolved.

**Closed by toastedcrumpets** 2020-09-15 20:28 UTC
