### ISSUE TITLE
Is the dimension right?

### ISSUE THREAD

**Issue by huijun-zhang** [toastedcrumpets/DynamO#54] opened 2015-11-17 10:44 UTC
Dear Marcus,
I think DynamO is able to run 2D simulations. But there may exist little bug about the equipartition.
We can first get 2D configuration, then use "--zero-vel 2" to set the Vz=0, and then use Anderson thermostat (Dimension=2) to control the simulation. But when I set -T 1.0, I get the ~0.66 output temperature (Here I used HardSphere system to test). This is 2/3 of T, I know you use KT=1/3(∑Vi). So does the pressure is also 2/3 of practical 2D pressure value?

Best

**Comment by toastedcrumpets** [comment] 2015-11-17 19:38
Yes, DynamO is fundamentally a 3D simulation tool. You can run 2D simulations in it, but some of the output plugins assume that the system is 3D, so temperature will be reported as 2/3rds of its actual value.

About the pressure, the same thing applies; however, the full pressure tensor is output by the code:
http://dynamomd.org/index.php/outputplugins#Pressure
So you will see some values (i.e. the Pzz value) are zero as expected. You can just directly take the two relevant diagonal pressure values from the tensor (Pxx+Pyy), or multiply the trace by 3/2 to get the correct pressure measurement.

Unfortunately, its too much work to make DynamO "smart" enough to understand when someone is working in 2D/1D. As the only problem is the output (not the simulation itself) I leave this to the user to correct (and its not difficult as you have found).

I'll close this as its not a bug, and no new features will be implemented.
Kind regards,
Marcus

**Closed by toastedcrumpets** 2015-11-17 19:38 UTC
