### ISSUE TITLE
Binary mixture of hard disks

### ISSUE THREAD

**Issue by edwinb-ai** [toastedcrumpets/DynamO#69] opened 2022-03-29 04:06 UTC
I am attempting to do some simulations of additive hard disks, i.e. in 2D, with the following command
```shell
dynamod -m 8 -x 64 -y 64 -z 1 --rectangular-box -d 0.6 --i1 2 -r 1.0 --f1 0.5 --i2 2048 --zero-vel 2 -o config.start.xml
```
From what I see in the command line, the mode `8` creates a binary hard sphere system. So I have tried to use the flags for zeroing out the velocity in the z-direction, as well as creating a rectangular box, much like in the monocomponent system. I am trying to create the configuration for the symmetric case and an equimolar composition. 
However, the command throws the following error
```shell
dynamod  Copyright (C) 2013  Marcus N Campbell Bannerman
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. See the licence you obtained with
the code
Main(): the argument ('0.5') for option '--i2' is invalid
Main(): Try using the debugging executable for more information on the error.
Singularity> sh additive.sh
dynamod  Copyright (C) 2013  Marcus N Campbell Bannerman
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. See the licence you obtained with
the code
NeighbourListScheduler: Neighbour List Scheduler Algorithm Loaded
Rescaler: Zeroing Momentum
Rescaler: WARNING Rescaling kT to 1
Rescaler: Current kT 0.168997
Simulation: Validating Species definitions
Simulation: Validating self-Interaction definitions
Simulation: Initialising the Dynamics
Simulation: DOF = 12288
Simulation: Initialising Scheduler Neighbourlist
CellNeighbourList: Cells Loaded
CellNeighbourList: Reinitialising on collision 0
CellNeighbourList: Cell diameter from interaction distance and overlink 0.0131786
CellNeighbourList: Cell diameter from unitary occupancy 0.015625
CellNeighbourList: Target cell width use after taking into account system size = 0.015625
CellNeighbourList: Cells 63,63,4
  Cell containers = 15876
  Cell Offset -0.0920028,-0.0920028,0.316617
  Cell Dimensions 1.38846,1.38846,-0.336825
  Lattice spacing 1.20445,1.20445,0.296408
  Supported Interaction range 0.929641
Main(): Exception thrown in [addCells] (/opt/DynamO/src/dynamo/dynamo/globals/cells.cpp:206)
  The system size is too small to support the range of interactions specified
  (i.e. the system is smaller than the interaction diameter of one particle).
Main(): Try using the debugging executable for more information on the error.
Exception Events = 0
```
I am not sure how to solve this issue, so it would be great if you could lend me a hand. Thanks in advance.

**Comment by toastedcrumpets** [comment] 2022-03-29 07:33
Hi @edwinb-ai! 
The issue is that dynamod is not aware you want a 2D system, so its making a 3D system the way you've specified (one particle "thick" in the z direction) but the neighbourlist can't work with that, it looks for something like 4 particle diameters in each direction the way I've programmed it.

The issue here is that dynamod mode 8 (binary spheres) hasn't got the same code as mode 0, where you can write
`./dynamod -m0 -x 7 -y 7 -z 1 --rectangular-box --i1 2 --zero-vel 2`
and the system guesses you're after a 2D system.

Although I could add this code with some work, the way I work with dynamo these days is to create configuration files directly using python and its XML tools (like lxml). I really only use `dynamod` to make examples as starting points for other people, as the configuration files have wayyyy too many variations/options/settings to make them all available in dynamod. Normally I'm hacking together all sorts of interactions, new events, multiple species etc.

For example, there are many ways you can setup your system. You could run 
`./dynamod -m0 -x 64 -y 64 -z 1 -d 0.8 --rectangular-box --i1 2 --zero-vel 2 -o config.xml`
To get a 2D system setup. Then you could edit the Interactions/Species to make a binary system, loading the XML file into python using lxml and making the changes there. Before you do this make sure you compare the 2D monocomponent system made with mode 0 and a 3D binary system made with mode 8 to see what changes are needed. This will then give you more control over the neighbourlist, which is a real issue for binary systems depending on the size ratio.

If you have issues with setting this up, just keep posting here and I'll try to answer them. I'm closing this issue as its not something I'm going to change in the code at this time, but I'm more than happy to help get you setup.

**Closed by toastedcrumpets** 2022-03-29 07:33 UTC

**Comment by edwinb-ai** [comment] 2022-03-29 16:21
Thank you for the quick reply. I suspected as much, so I will try to create the configuration as you have suggested. Thanks!
